/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.green369258.swig;

public class Rect {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Rect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Rect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UnixJNI.delete_Rect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    UnixJNI.Rect_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return UnixJNI.Rect_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    UnixJNI.Rect_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return UnixJNI.Rect_y_get(swigCPtr, this);
  }

  public void setW(int value) {
    UnixJNI.Rect_w_set(swigCPtr, this, value);
  }

  public int getW() {
    return UnixJNI.Rect_w_get(swigCPtr, this);
  }

  public void setH(int value) {
    UnixJNI.Rect_h_set(swigCPtr, this, value);
  }

  public int getH() {
    return UnixJNI.Rect_h_get(swigCPtr, this);
  }

  public Rect() {
    this(UnixJNI.new_Rect(), true);
  }

}
