/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.green369258.swig;

public interface UnixConstants {
  public final static int MAX_WIDTH = 640;
  public final static int MY_TEST_MAC = UnixJNI.MY_TEST_MAC_get();
  public final static int MAX_HEIGHT = UnixJNI.MAX_HEIGHT_get();
}
