/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.green369258.swig;

public class UnixJNI {
  public final static native long getuid();
  public final static native void counter_set(int jarg1);
  public final static native int counter_get();
  public final static native int counter_readonly_get();
  public final static native int MY_TEST_MAC_get();
  public final static native int MAX_HEIGHT_get();
  public final static native void Rect_x_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_x_get(long jarg1, Rect jarg1_);
  public final static native void Rect_y_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_y_get(long jarg1, Rect jarg1_);
  public final static native void Rect_w_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_w_get(long jarg1, Rect jarg1_);
  public final static native void Rect_h_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_h_get(long jarg1, Rect jarg1_);
  public final static native long new_Rect();
  public final static native void delete_Rect(long jarg1);
  public final static native void Point_x_set(long jarg1, Point jarg1_, int jarg2);
  public final static native int Point_x_get(long jarg1, Point jarg1_);
  public final static native void Point_y_set(long jarg1, Point jarg1_, int jarg2);
  public final static native int Point_y_get(long jarg1, Point jarg1_);
  public final static native void Point_temp_set(long jarg1, Point jarg1_, long jarg2, Rect jarg2_);
  public final static native long Point_temp_get(long jarg1, Point jarg1_);
  public final static native long new_Point();
  public final static native void delete_Point(long jarg1);
  public final static native int getPoint(long jarg1, Point jarg1_);
}
