/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.green369258.swig;

public class Unix implements UnixConstants {
  public static long getuid() {
    return UnixJNI.getuid();
  }

  public static void setCounter(int value) {
    UnixJNI.counter_set(value);
  }

  public static int getCounter() {
    return UnixJNI.counter_get();
  }

  public static int getCounter_readonly() {
    return UnixJNI.counter_readonly_get();
  }

  public static int getPoint(Point p) {
    return UnixJNI.getPoint(Point.getCPtr(p), p);
  }

}
